spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa

kakao:
  api:
    url: https://dapi.kakao.com/v3/search/book?
    key: KakaoAK 54a6c384ec25e398d6b7e5fba3fad494

naver:
  api:
    url: https://openapi.naver.com/v1/search/book_adv.json?
    id: 2GNd6CCIbCzgAJt7MGWF
    secret: hOqmSBFivh
